// Generated by gencpp from file realsense_camera/CameraConfiguration.msg
// DO NOT EDIT!


#ifndef REALSENSE_CAMERA_MESSAGE_CAMERACONFIGURATION_H
#define REALSENSE_CAMERA_MESSAGE_CAMERACONFIGURATION_H

#include <ros/service_traits.h>


#include <realsense_camera/CameraConfigurationRequest.h>
#include <realsense_camera/CameraConfigurationResponse.h>


namespace realsense_camera
{

struct CameraConfiguration
{

typedef CameraConfigurationRequest Request;
typedef CameraConfigurationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraConfiguration
} // namespace realsense_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_camera::CameraConfiguration > {
  static const char* value()
  {
    return "2c284890309b239ca006a289ca29b4d1";
  }

  static const char* value(const ::realsense_camera::CameraConfiguration&) { return value(); }
};

template<>
struct DataType< ::realsense_camera::CameraConfiguration > {
  static const char* value()
  {
    return "realsense_camera/CameraConfiguration";
  }

  static const char* value(const ::realsense_camera::CameraConfiguration&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_camera::CameraConfigurationRequest> should match 
// service_traits::MD5Sum< ::realsense_camera::CameraConfiguration > 
template<>
struct MD5Sum< ::realsense_camera::CameraConfigurationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_camera::CameraConfiguration >::value();
  }
  static const char* value(const ::realsense_camera::CameraConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_camera::CameraConfigurationRequest> should match 
// service_traits::DataType< ::realsense_camera::CameraConfiguration > 
template<>
struct DataType< ::realsense_camera::CameraConfigurationRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_camera::CameraConfiguration >::value();
  }
  static const char* value(const ::realsense_camera::CameraConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_camera::CameraConfigurationResponse> should match 
// service_traits::MD5Sum< ::realsense_camera::CameraConfiguration > 
template<>
struct MD5Sum< ::realsense_camera::CameraConfigurationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_camera::CameraConfiguration >::value();
  }
  static const char* value(const ::realsense_camera::CameraConfigurationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_camera::CameraConfigurationResponse> should match 
// service_traits::DataType< ::realsense_camera::CameraConfiguration > 
template<>
struct DataType< ::realsense_camera::CameraConfigurationResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_camera::CameraConfiguration >::value();
  }
  static const char* value(const ::realsense_camera::CameraConfigurationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_CAMERA_MESSAGE_CAMERACONFIGURATION_H
