// Generated by gencpp from file realsense_camera/ForcePower.msg
// DO NOT EDIT!


#ifndef REALSENSE_CAMERA_MESSAGE_FORCEPOWER_H
#define REALSENSE_CAMERA_MESSAGE_FORCEPOWER_H

#include <ros/service_traits.h>


#include <realsense_camera/ForcePowerRequest.h>
#include <realsense_camera/ForcePowerResponse.h>


namespace realsense_camera
{

struct ForcePower
{

typedef ForcePowerRequest Request;
typedef ForcePowerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ForcePower
} // namespace realsense_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_camera::ForcePower > {
  static const char* value()
  {
    return "0a07d78fa0214ec8d773e5045aa5087a";
  }

  static const char* value(const ::realsense_camera::ForcePower&) { return value(); }
};

template<>
struct DataType< ::realsense_camera::ForcePower > {
  static const char* value()
  {
    return "realsense_camera/ForcePower";
  }

  static const char* value(const ::realsense_camera::ForcePower&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_camera::ForcePowerRequest> should match 
// service_traits::MD5Sum< ::realsense_camera::ForcePower > 
template<>
struct MD5Sum< ::realsense_camera::ForcePowerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_camera::ForcePower >::value();
  }
  static const char* value(const ::realsense_camera::ForcePowerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_camera::ForcePowerRequest> should match 
// service_traits::DataType< ::realsense_camera::ForcePower > 
template<>
struct DataType< ::realsense_camera::ForcePowerRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_camera::ForcePower >::value();
  }
  static const char* value(const ::realsense_camera::ForcePowerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_camera::ForcePowerResponse> should match 
// service_traits::MD5Sum< ::realsense_camera::ForcePower > 
template<>
struct MD5Sum< ::realsense_camera::ForcePowerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_camera::ForcePower >::value();
  }
  static const char* value(const ::realsense_camera::ForcePowerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_camera::ForcePowerResponse> should match 
// service_traits::DataType< ::realsense_camera::ForcePower > 
template<>
struct DataType< ::realsense_camera::ForcePowerResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_camera::ForcePower >::value();
  }
  static const char* value(const ::realsense_camera::ForcePowerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_CAMERA_MESSAGE_FORCEPOWER_H
