// Generated by gencpp from file realsense_camera/SetPower.msg
// DO NOT EDIT!


#ifndef REALSENSE_CAMERA_MESSAGE_SETPOWER_H
#define REALSENSE_CAMERA_MESSAGE_SETPOWER_H

#include <ros/service_traits.h>


#include <realsense_camera/SetPowerRequest.h>
#include <realsense_camera/SetPowerResponse.h>


namespace realsense_camera
{

struct SetPower
{

typedef SetPowerRequest Request;
typedef SetPowerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPower
} // namespace realsense_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_camera::SetPower > {
  static const char* value()
  {
    return "a0a242e9c383e4ceb1b4d16e36607d54";
  }

  static const char* value(const ::realsense_camera::SetPower&) { return value(); }
};

template<>
struct DataType< ::realsense_camera::SetPower > {
  static const char* value()
  {
    return "realsense_camera/SetPower";
  }

  static const char* value(const ::realsense_camera::SetPower&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_camera::SetPowerRequest> should match 
// service_traits::MD5Sum< ::realsense_camera::SetPower > 
template<>
struct MD5Sum< ::realsense_camera::SetPowerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_camera::SetPower >::value();
  }
  static const char* value(const ::realsense_camera::SetPowerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_camera::SetPowerRequest> should match 
// service_traits::DataType< ::realsense_camera::SetPower > 
template<>
struct DataType< ::realsense_camera::SetPowerRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_camera::SetPower >::value();
  }
  static const char* value(const ::realsense_camera::SetPowerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_camera::SetPowerResponse> should match 
// service_traits::MD5Sum< ::realsense_camera::SetPower > 
template<>
struct MD5Sum< ::realsense_camera::SetPowerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_camera::SetPower >::value();
  }
  static const char* value(const ::realsense_camera::SetPowerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_camera::SetPowerResponse> should match 
// service_traits::DataType< ::realsense_camera::SetPower > 
template<>
struct DataType< ::realsense_camera::SetPowerResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_camera::SetPower >::value();
  }
  static const char* value(const ::realsense_camera::SetPowerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_CAMERA_MESSAGE_SETPOWER_H
