// Generated by gencpp from file rc_car_msgs/CarInfo.msg
// DO NOT EDIT!


#ifndef RC_CAR_MSGS_MESSAGE_CARINFO_H
#define RC_CAR_MSGS_MESSAGE_CARINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rc_car_msgs
{
template <class ContainerAllocator>
struct CarInfo_
{
  typedef CarInfo_<ContainerAllocator> Type;

  CarInfo_()
    : header()
    , throttle(0.0)
    , steer(0.0)  {
    }
  CarInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , throttle(0.0)
    , steer(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _throttle_type;
  _throttle_type throttle;

   typedef float _steer_type;
  _steer_type steer;




  typedef boost::shared_ptr< ::rc_car_msgs::CarInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rc_car_msgs::CarInfo_<ContainerAllocator> const> ConstPtr;

}; // struct CarInfo_

typedef ::rc_car_msgs::CarInfo_<std::allocator<void> > CarInfo;

typedef boost::shared_ptr< ::rc_car_msgs::CarInfo > CarInfoPtr;
typedef boost::shared_ptr< ::rc_car_msgs::CarInfo const> CarInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rc_car_msgs::CarInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rc_car_msgs::CarInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rc_car_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rc_car_msgs': ['/home/nvidia/jetson-car/src/rc_car_msgs/msg', '/home/nvidia/jetson-car/src/rc_car_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rc_car_msgs::CarInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rc_car_msgs::CarInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rc_car_msgs::CarInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rc_car_msgs::CarInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rc_car_msgs::CarInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rc_car_msgs::CarInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rc_car_msgs::CarInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fde3dbdce53ea8efc0e0dd6ef6da3ed4";
  }

  static const char* value(const ::rc_car_msgs::CarInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfde3dbdce53ea8efULL;
  static const uint64_t static_value2 = 0xc0e0dd6ef6da3ed4ULL;
};

template<class ContainerAllocator>
struct DataType< ::rc_car_msgs::CarInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rc_car_msgs/CarInfo";
  }

  static const char* value(const ::rc_car_msgs::CarInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rc_car_msgs::CarInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header  header\n\
float32 throttle\n\
float32 steer\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::rc_car_msgs::CarInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rc_car_msgs::CarInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.throttle);
      stream.next(m.steer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rc_car_msgs::CarInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rc_car_msgs::CarInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "throttle: ";
    Printer<float>::stream(s, indent + "  ", v.throttle);
    s << indent << "steer: ";
    Printer<float>::stream(s, indent + "  ", v.steer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RC_CAR_MSGS_MESSAGE_CARINFO_H
