# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from realsense_camera/GetIMUInfoRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GetIMUInfoRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "realsense_camera/GetIMUInfoRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetIMUInfoRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from realsense_camera/GetIMUInfoResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg
import realsense_camera.msg

class GetIMUInfoResponse(genpy.Message):
  _md5sum = "fcce7f85a63907f26a3912a7632e9630"
  _type = "realsense_camera/GetIMUInfoResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """IMUInfo accel
IMUInfo gyro


================================================================================
MSG: realsense_camera/IMUInfo
# header.frame_id is either set to "imu_accel" or "imu_gyro"
# to distinguish between "accel" and "gyro" info.
std_msgs/Header header
float64[12] data
float64[3] noise_variances
float64[3] bias_variances
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['accel','gyro']
  _slot_types = ['realsense_camera/IMUInfo','realsense_camera/IMUInfo']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       accel,gyro

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetIMUInfoResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.accel is None:
        self.accel = realsense_camera.msg.IMUInfo()
      if self.gyro is None:
        self.gyro = realsense_camera.msg.IMUInfo()
    else:
      self.accel = realsense_camera.msg.IMUInfo()
      self.gyro = realsense_camera.msg.IMUInfo()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.accel.header.seq, _x.accel.header.stamp.secs, _x.accel.header.stamp.nsecs))
      _x = self.accel.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_12d().pack(*self.accel.data))
      buff.write(_get_struct_3d().pack(*self.accel.noise_variances))
      buff.write(_get_struct_3d().pack(*self.accel.bias_variances))
      _x = self
      buff.write(_get_struct_3I().pack(_x.gyro.header.seq, _x.gyro.header.stamp.secs, _x.gyro.header.stamp.nsecs))
      _x = self.gyro.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_12d().pack(*self.gyro.data))
      buff.write(_get_struct_3d().pack(*self.gyro.noise_variances))
      buff.write(_get_struct_3d().pack(*self.gyro.bias_variances))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.accel is None:
        self.accel = realsense_camera.msg.IMUInfo()
      if self.gyro is None:
        self.gyro = realsense_camera.msg.IMUInfo()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.accel.header.seq, _x.accel.header.stamp.secs, _x.accel.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.accel.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.accel.header.frame_id = str[start:end]
      start = end
      end += 96
      self.accel.data = _get_struct_12d().unpack(str[start:end])
      start = end
      end += 24
      self.accel.noise_variances = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.accel.bias_variances = _get_struct_3d().unpack(str[start:end])
      _x = self
      start = end
      end += 12
      (_x.gyro.header.seq, _x.gyro.header.stamp.secs, _x.gyro.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gyro.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.gyro.header.frame_id = str[start:end]
      start = end
      end += 96
      self.gyro.data = _get_struct_12d().unpack(str[start:end])
      start = end
      end += 24
      self.gyro.noise_variances = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.gyro.bias_variances = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.accel.header.seq, _x.accel.header.stamp.secs, _x.accel.header.stamp.nsecs))
      _x = self.accel.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(self.accel.data.tostring())
      buff.write(self.accel.noise_variances.tostring())
      buff.write(self.accel.bias_variances.tostring())
      _x = self
      buff.write(_get_struct_3I().pack(_x.gyro.header.seq, _x.gyro.header.stamp.secs, _x.gyro.header.stamp.nsecs))
      _x = self.gyro.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(self.gyro.data.tostring())
      buff.write(self.gyro.noise_variances.tostring())
      buff.write(self.gyro.bias_variances.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.accel is None:
        self.accel = realsense_camera.msg.IMUInfo()
      if self.gyro is None:
        self.gyro = realsense_camera.msg.IMUInfo()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.accel.header.seq, _x.accel.header.stamp.secs, _x.accel.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.accel.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.accel.header.frame_id = str[start:end]
      start = end
      end += 96
      self.accel.data = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=12)
      start = end
      end += 24
      self.accel.noise_variances = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.accel.bias_variances = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      _x = self
      start = end
      end += 12
      (_x.gyro.header.seq, _x.gyro.header.stamp.secs, _x.gyro.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gyro.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.gyro.header.frame_id = str[start:end]
      start = end
      end += 96
      self.gyro.data = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=12)
      start = end
      end += 24
      self.gyro.noise_variances = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.gyro.bias_variances = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_12d = None
def _get_struct_12d():
    global _struct_12d
    if _struct_12d is None:
        _struct_12d = struct.Struct("<12d")
    return _struct_12d
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
class GetIMUInfo(object):
  _type          = 'realsense_camera/GetIMUInfo'
  _md5sum = 'fcce7f85a63907f26a3912a7632e9630'
  _request_class  = GetIMUInfoRequest
  _response_class = GetIMUInfoResponse
